To: crypt (at) bis.doc.gov, enc (at) nsa.gov, web_site (at) bis.doc.gov
Cc: Info-ZIP-Dev (at) goatley.com
Subject: TSU NOTIFICATION - Encryption (Info-ZIP zcrypt.zip)
Date: Nov 5, 2015 2:34 AM

   SUBMISSION TYPE:       TSU
   SUBMITTED BY:          Edward Gordon
   SUBMITTED FOR:         The Info-ZIP group (an informal, Internet-based
                          collection of software developers with the contact
                          address given in next item)
   POINT OF CONTACT:      Info-ZIP-Dev (at) goatley.com
   PHONE and/or FAX:      n/a
   MANUFACTURER:          n/a
   PRODUCT NAME/MODEL #:  zcrypt
   ECCN:                  5D002

   NOTIFICATION:

           ftp://ftp.info-zip.org/pub/infozip/crypt/zcrypt.zip

